### ISSUE TITLE
Install instructions wrong

### ISSUE THREAD

**Issue by hardillb** [idocme/translate-red-node#1]
Hi,

The install instructions still point to the details of the node this is based on.

Also any reason you didn't work with the original node owner to improve it rather than fork it?

**Comment by idocme** [comment]
Hi hardillb,
I fixed the install instructions.
And I needed a quick solution for a small service I made, so iv'e forked and gave credit (based on this package) and upload it so the person who wanted to use the service I built could use it isntantly.
